### ISSUE TITLE
Suggestion: Terminology Primer Page

### ISSUE THREAD

**Issue by irishtechie** [100daysofkubernetes/100DaysOfKubernetes#10]
Hi Anais and Rishab,

Awesome project. Thank you for creating it.

What do you think about adding a "Terminology Primer" page to the "Let's get started" section. It could be a glossary of sorts with the most common terms that people will encounter as they are on their 100 Days of Kubernetes journey. We could add one line explanations for each term.

I think this might help people who are brand new to the space.

If you think it will be useful, I can pull something together over the next day or two and submit a pull request.

Let me know what you think. 

Thanks

Karl Cooke (@Karl_ITNerd)

**Comment by AnaisUrlichs** [comment]
Hey Karl, 
I think that sounds amazing! Do you want to have it under a separate section that is just focused on the glossary?
It would be amazing if you want to give it a go. Obv. I am here to help and others are probably excited to contribute, too 🙂 
Lmk if you have any questions!

**Comment by irishtechie** [comment]
Glossary sounds like a good spot! I'll give it a go over next couple days and then, once it's up it can grow from there.

**Comment by irishtechie** [comment]
I have this mostly completed. I'll submit as a PR later.

**Comment by AnaisUrlichs** [comment]
@irishtechie great, thank you! Please link to this issue :)

**Comment by irishtechie** [comment]
@AnaisUrlichs, will do. Thank you.

**Comment by irishtechie** [comment]
@AnaisUrlichs I feel a bit dumb but the option to link with a PR on the right isn't editable by me. Perhaps I am missing something.
